### ISSUE TITLE
compiler.run() - Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by droid51** [sap9433/filewatcher-webpack-plugin#2]
Hi there,

how I can take my own onChangeCallback Function? How I can get the compiler instance?
Thx!

![grafik](https://user-images.githubusercontent.com/8912561/36430550-aff49444-1655-11e8-9da7-97af4f9170ee.png)

**Comment by droid51** [comment]
current "workaround", I modified your module and call my functions with more args
![grafik](https://user-images.githubusercontent.com/8912561/36432149-bf3d6a26-1659-11e8-9659-bfb89e08b972.png)

and besides... In my Custom-Callback-Function I moved 2 lines.
![grafik](https://user-images.githubusercontent.com/8912561/36432284-1e997e24-165a-11e8-8577-146c25ab9be6.png)
~1. I think watcher should only close on error, or?~ (forget it...)
2. end-message should be inside the run-callback, or?

thx!

**Comment by sap9433** [comment]
Existing code
```.on(
        'change',
        options.onChangeCallback || ...
```
So if we just provide custom `options.onChangeCallback` while initializing, then it would take precedence. I don't think source code needs to be changed.

**Comment by droid51** [comment]
I think you understand my point :-) sorry if I communicate too complicate :-D

I can't use a custom function, because i can't call the function compiler.run(), because i don't have the compiler instance inside my custom function. I only change that I got this instance

thx!

**Comment by droid51** [comment]
ok, last try :-(
problem still exists

my example code (for this example onChangeCallback is the same function you use internal)
![grafik](https://user-images.githubusercontent.com/8912561/37643329-6a711fc4-2c20-11e8-954c-2c9f081ac003.png)

But than you got
![grafik](https://user-images.githubusercontent.com/8912561/37643390-a2304dcc-2c20-11e8-90f2-30856411099a.png)

this is th reason that i would give the custum function more attributes than path. you need **compiler** and **watcher**

thx!
