### ISSUE TITLE
Access compiler in onChangeCallback

### ISSUE THREAD

**Issue by fabienpinel** [sap9433/filewatcher-webpack-plugin#6]
Hi,
I'm trying to override the default behavior of onChangeCallback in order to add some logic. But I can't access the `compiler` variable in order to call the compiler at the end of the function. I understand that in your example it works because you're in the plugin apply function which has it injected by default but how to access it without being in an aplpy function ?
cc @sap9433 

Thanks in advance for your help
Fabien

**Comment by motin** [comment]
Change this line: https://github.com/sap9433/filewatcher-webpack-plugin/blob/3f264b98d07df8783df61c4ad27472938a2622bb/index.js#L41 from

```
        options.onChangeCallback ||
```
to 
```
        options.onChangeCallback.bind({compiler}) ||
```

You can the access the compiler object in your callback as this.compiler.

PR to bind all custom callbacks in this manner: https://github.com/sap9433/filewatcher-webpack-plugin/pull/8
